FROM quay.io/arloor/ubi-micro:10
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone;
ARG TARGET_PATH=/x86_64-unknown-linux-gnu
COPY target${TARGET_PATH}/release/hyperway /
COPY target${TARGET_PATH}/release/hyperway_controller /
ENTRYPOINT ["/hyperway"]
