FROM docker.io/redhat/ubi10:latest
RUN dnf install -y ca-certificates iproute zlib elfutils-libelf tzdata
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone;
COPY target/release/hyperway hyperway
COPY target/release/hyperway_controller hyperway_controller
ENTRYPOINT ["./hyperway"]
