FROM debian:bookworm
COPY target/release/hyperway hyperway
COPY target/release/hyperway_controller hyperway_controller
RUN apt-get update \
    && apt-get upgrade -y ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["./hyperway"]
